# Generated by Django 5.1.7 on 2025-10-01 19:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('binance', 'Binance'), ('bingx', 'BingX'), ('bybit', 'Bybit'), ('bitmart', 'Bitmart')], default='binance', max_length=20)),
                ('market', models.CharField(choices=[('spot', 'Spot'), ('future', 'Future')], default='spot', max_length=10)),
                ('symbols', models.CharField(default='KAITO/USDT,LTC/USDT,XRP/USDT', max_length=200)),
                ('start_capital', models.DecimalField(decimal_places=8, default=Decimal('100.0'), max_digits=20)),
                ('trade_amount', models.DecimalField(decimal_places=8, default=Decimal('10.0'), max_digits=20)),
                ('take_profit', models.DecimalField(decimal_places=2, default=Decimal('0.30'), max_digits=5)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=5)),
                ('api_key', models.CharField(blank=True, max_length=100, null=True)),
                ('secret_key', models.CharField(blank=True, max_length=100, null=True)),
                ('countdown', models.IntegerField(default=1)),
                ('countdown_reset_indicators', models.IntegerField(default=60)),
                ('time_interval', models.IntegerField(default=2)),
                ('is_running', models.BooleanField(default=False)),
                ('sales_stop_threshold', models.DecimalField(decimal_places=8, default=Decimal('10.0'), max_digits=20)),
                ('div_DVA_prev_NDA_threshold_buy', models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=20)),
                ('deltadelta_threshold_buy', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('nda_threshold_buy', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BacktestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=40)),
                ('progress', models.IntegerField(default=0)),
                ('result', models.JSONField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_start_time', models.DateTimeField(blank=True, null=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.configuration')),
            ],
        ),
        migrations.CreateModel(
            name='DataLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=80)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('max_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('min_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('current_da', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('nda', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('prev_da', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('prev_nda', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('dva', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('deltadelta', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('div_DVA_prev_NDA', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('mvd', models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_logs', to='trading.configuration')),
            ],
        ),
        migrations.CreateModel(
            name='TradingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('symbol', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('fee_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('pl_nominal', models.DecimalField(decimal_places=8, max_digits=20)),
                ('current_capital', models.DecimalField(decimal_places=8, max_digits=20)),
                ('order_id', models.CharField(max_length=100)),
                ('pl_relative', models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20)),
                ('total_pl', models.DecimalField(decimal_places=8, max_digits=20)),
                ('tank', models.DecimalField(decimal_places=8, max_digits=20)),
                ('bid_price', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('ask_price', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='trading.configuration')),
            ],
        ),
    ]
