# Generated by Django 5.1.7 on 2026-01-08 06:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='stop_loss',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='symbols',
            field=models.CharField(default='BTC/USDT,ETH/USDT,SOL/USDT,LTC/USDT,XRP/USDT', max_length=200),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='take_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=5),
        ),
    ]
