# Generated by Django 5.1.7 on 2026-01-09 00:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_configuration_stop_loss_alter_configuration_symbols_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='is_running',
        ),
        migrations.RemoveField(
            model_name='tradinglog',
            name='ask_price',
        ),
        migrations.RemoveField(
            model_name='tradinglog',
            name='bid_price',
        ),
        migrations.RemoveField(
            model_name='tradinglog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tradinglog',
            name='time',
        ),
        migrations.AddField(
            model_name='configuration',
            name='name',
            field=models.CharField(default='Default Config', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuration',
            name='api_key',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='countdown_reset_indicators',
            field=models.BooleanField(default=False, help_text='Indikatoren nach Trade zurücksetzen'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='div_DVA_prev_NDA_threshold_buy',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='exchange',
            field=models.CharField(choices=[('binance', 'Binance'), ('bingx', 'BingX'), ('bybit', 'Bybit'), ('bitmart', 'Bitmart')], max_length=20),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='fee',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.1'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='market',
            field=models.CharField(choices=[('spot', 'Spot'), ('futures', 'Futures')], default='spot', max_length=20),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='sales_stop_threshold',
            field=models.FloatField(default=0.0, help_text='Prozentualer Verlust, ab dem verkauft wird'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='secret_key',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='stop_loss',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.5'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='symbols',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='take_profit',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.5'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datalog',
            name='symbol',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tradinglog',
            name='order_id',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='tradinglog',
            name='pl_relative',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tradinglog',
            name='symbol',
            field=models.CharField(max_length=30),
        ),
        migrations.AddIndex(
            model_name='datalog',
            index=models.Index(fields=['configuration', 'symbol', 'timestamp'], name='trading_dat_configu_ef5850_idx'),
        ),
    ]
