# Generated by Django 5.1.7 on 2026-01-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_remove_configuration_is_running_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='is_running',
            field=models.BooleanField(default=False, help_text='Gibt an, ob der Bot aktuell läuft'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='symbols',
            field=models.CharField(default='BTC/USDT,ETH/USDT,SOL/USDT,KAITO/USDT,LTC/USDT,XRP/USDT', max_length=200),
        ),
    ]
