# Generated by Django 5.1.7 on 2026-01-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_configuration_is_running_alter_configuration_symbols'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='exchange',
            field=models.CharField(choices=[('binance', 'Binance'), ('bingx', 'BingX'), ('bybit', 'Bybit'), ('bitmart', 'Bitmart')], default='binance', max_length=20),
        ),
    ]
