# Generated by Django 5.1.4 on 2026-07-14 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_alter_configuration_exchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(help_text="z.B. 'trading_bot.main_loop', 'config_activate'", max_length=100)),
                ('message', models.TextField()),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_logs', to='trading.configuration')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
