# Generated by Django 5.1.4 on 2026-08-19 20:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_errorlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backtesttask',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='datalog',
            options={'ordering': ['timestamp', 'id']},
        ),
        migrations.AlterModelOptions(
            name='tradinglog',
            options={'ordering': ['timestamp', 'id']},
        ),
        migrations.AlterField(
            model_name='backtesttask',
            name='progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='backtesttask',
            name='status',
            field=models.CharField(choices=[('pending', 'Ausstehend'), ('scheduled', 'Geplant'), ('running', 'Läuft'), ('paused', 'Pausiert'), ('completed', 'Abgeschlossen'), ('cancelled', 'Abgebrochen'), ('failed', 'Fehlgeschlagen')], default='pending', max_length=40),
        ),
        migrations.AlterField(
            model_name='backtesttask',
            name='symbol',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='countdown',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='countdown_reset_indicators',
            field=models.BooleanField(default=False, help_text='Indikatoren nach einem Verkauf zurücksetzen.'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='exchange',
            field=models.CharField(choices=[('binance', 'Binance'), ('bingx', 'BingX'), ('bybit', 'Bybit'), ('bitmart', 'BitMart')], default='binance', max_length=20),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='fee',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.1'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='is_running',
            field=models.BooleanField(default=False, help_text='Gibt an, ob der Bot aktuell laufen soll.'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='sales_stop_threshold',
            field=models.FloatField(default=0.0, help_text='Maximaler Verlust des Gesamtkapitals in Prozent (0 = deaktiviert).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='start_capital',
            field=models.DecimalField(decimal_places=8, default=Decimal('100'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))]),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='stop_loss',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.5'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='symbols',
            field=models.CharField(default='BTC/USDT,ETH/USDT,SOL/USDT,LTC/USDT,XRP/USDT', max_length=200),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='take_profit',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.5'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='time_interval',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='trade_amount',
            field=models.DecimalField(decimal_places=8, default=Decimal('10'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))]),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='source',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='backtesttask',
            index=models.Index(fields=['status', 'scheduled_start_time'], name='trading_bac_status_69610d_idx'),
        ),
        migrations.AddIndex(
            model_name='tradinglog',
            index=models.Index(fields=['configuration', 'symbol', 'timestamp'], name='trading_tra_configu_35e343_idx'),
        ),
    ]
