# Generated by Django 5.2.17 on 2026-08-19 21:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_validation_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='stop_loss',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.5'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='take_profit',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.5'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
