# Generated by Django 5.2.17 on 2026-08-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_tighten_risk_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='exception_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warnung'), ('error', 'Fehler'), ('critical', 'Kritisch')], default='error', max_length=20),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['configuration', 'resolved', '-timestamp'], name='trading_err_configu_b62355_idx'),
        ),
    ]
