# Generated by Django 5.2.17 on 2026-08-20 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_enrich_error_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='time_interval',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)]),
        ),
    ]
