# Generated by Django 5.2.17 on 2026-08-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_cap_poll_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='exchange',
            field=models.CharField(choices=[('binance', 'Binance'), ('bingx', 'BingX'), ('bybit', 'Bybit'), ('bitmart', 'BitMart'), ('bitunix', 'Bitunix')], default='binance', max_length=20),
        ),
    ]
